#!/bin/bash

# Define the allowed types and scopes for conventional commits.
types="build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test"

# Create a regex for a conventional commit.
conventional_commit_regex="^(${types})!?: .+$"

# Get the commit message from the provided file path.
commit_message=$(cat "$1")

# ANSI color codes for formatting output.
color_reset='\033[0m'     # Text Reset
color_green='\033[32m'    # Green
color_red='\033[31m'      # Red

# Check if the commit message meets the conventional commit standards.
if [[ $commit_message =~ $conventional_commit_regex ]]; then
   echo -e "
   ${color_green}The commit message adheres to conventional commit standards.${color_reset}
   
   "
   exit 0
fi

# Print an error message if the commit message does not meet the standard.
echo -e "

${color_red}Error: The commit message does not meet the conventional commit standard.${color_reset}

For this project, you can use:
   - Types: ${types}
   
More details at: [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)


"
exit 1